-- MySQL Script generated by MySQL Workbench
-- jue 26 dic 2024 14:35:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pais` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`departamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pais_id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`, `pais_id`),
  INDEX `fk_departamento_pais1_idx` (`pais_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_departamento_pais1`
    FOREIGN KEY (`pais_id`)
    REFERENCES `mydb`.`pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ciudad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ciudad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `departamento_id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`, `departamento_id`),
  INDEX `fk_ciudad_departamento1_idx` (`departamento_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_ciudad_departamento1`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `mydb`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`direccion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`direccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ciudad_id` INT NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`, `ciudad_id`),
  INDEX `fk_direccion_ciudad1_idx` (`ciudad_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_direccion_ciudad1`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `mydb`.`ciudad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`restaurante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`restaurante` ;

CREATE TABLE IF NOT EXISTS `mydb`.`restaurante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `correo` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `estado` ENUM("ACTIVO", "INACTIVO") NULL,
  `id_atenticacion` VARCHAR(255) NULL,
  `id_transaccional` VARCHAR(255) NULL,
  `capacidad_reservas` TINYINT UNSIGNED NULL,
  `direccion_id` INT NOT NULL,
  PRIMARY KEY (`id`, `direccion_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_restaurante_direccion1_idx` (`direccion_id` ASC) VISIBLE,
  CONSTRAINT `fk_restaurante_direccion1`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `mydb`.`direccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reservas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reservas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `cantidad` TINYINT UNSIGNED NOT NULL,
  `estado` ENUM("PENDIENTE", "RESERVADO", "CANCELADO") NOT NULL,
  `restaurante_id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `restaurante_id`),
  INDEX `fk_reservas_restaurante1_idx` (`restaurante_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_reservas_restaurante1`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `mydb`.`restaurante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mesa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`mesa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`mesa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `etiqueta` VARCHAR(45) NOT NULL,
  `capacidad` INT UNSIGNED NOT NULL,
  `restaurante_id` INT NOT NULL,
  PRIMARY KEY (`id`, `restaurante_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_mesa_restaurante1_idx` (`restaurante_id` ASC) VISIBLE,
  CONSTRAINT `fk_mesa_restaurante1`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `mydb`.`restaurante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `id_transaccional` VARCHAR(255) NULL,
  `mesa_id` INT NOT NULL,
  PRIMARY KEY (`id`, `mesa_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_pedido_mesa1_idx` (`mesa_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_mesa1`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `mydb`.`mesa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`platillo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`platillo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`platillo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL,
  `precio` DECIMAL(15,2) UNSIGNED NOT NULL,
  `existencias` INT UNSIGNED NOT NULL,
  `restaurante_id` INT NOT NULL,
  PRIMARY KEY (`id`, `restaurante_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_platillo_restaurante1_idx` (`restaurante_id` ASC) VISIBLE,
  CONSTRAINT `fk_platillo_restaurante1`
    FOREIGN KEY (`restaurante_id`)
    REFERENCES `mydb`.`restaurante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`platillo_has_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`platillo_has_pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`platillo_has_pedido` (
  `platillo_id` INT NOT NULL,
  `pedido_id` INT NOT NULL,
  `cantidad` INT UNSIGNED NOT NULL,
  `estado` ENUM("ENTREGADO", "PENDIENTE") NOT NULL,
  `total` DECIMAL(15,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`platillo_id`, `pedido_id`),
  INDEX `fk_platillo_has_pedido_pedido1_idx` (`pedido_id` ASC) VISIBLE,
  INDEX `fk_platillo_has_pedido_platillo1_idx` (`platillo_id` ASC) VISIBLE,
  CONSTRAINT `fk_platillo_has_pedido_platillo1`
    FOREIGN KEY (`platillo_id`)
    REFERENCES `mydb`.`platillo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_platillo_has_pedido_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `mydb`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mesa_has_reservas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`mesa_has_reservas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`mesa_has_reservas` (
  `mesa_id` INT NOT NULL,
  `reservas_id` INT NOT NULL,
  PRIMARY KEY (`mesa_id`, `reservas_id`),
  INDEX `fk_mesa_has_reservas_reservas1_idx` (`reservas_id` ASC) VISIBLE,
  INDEX `fk_mesa_has_reservas_mesa1_idx` (`mesa_id` ASC) VISIBLE,
  CONSTRAINT `fk_mesa_has_reservas_mesa1`
    FOREIGN KEY (`mesa_id`)
    REFERENCES `mydb`.`mesa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mesa_has_reservas_reservas1`
    FOREIGN KEY (`reservas_id`)
    REFERENCES `mydb`.`reservas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
